export const STRATEGIC_OPS_LABELS = {
  pageTitle: 'مركز العمليات الاستراتيجي',
  pageSubtitle: 'تحليل تشغيلي شامل من سجلات الأداء اليومية التاريخية في Google Sheets',
  startDate: 'تاريخ البداية',
  endDate: 'تاريخ النهاية',
  zone: 'الزون',
  allZones: 'كل الزونات',
  supervisor: 'المشرف',
  allSupervisors: 'كل المشرفين',
  runAnalysis: 'تشغيل التحليل',
  analyzing: 'جاري التحليل…',
  exportExcel: 'تصدير التقرير (Excel)',
  exportPdf: 'تصدير التقرير (PDF)',
  copyChatGpt: 'نسخ التحليل الكامل لـ ChatGPT',
  selectFilters: 'اختر الفلاتر واضغط «تشغيل التحليل» لإنشاء التقرير.',

  executiveSummary: '١ — الملخص التنفيذي',
  activityDistribution: '٢ — توزيع نشاط الطيارين',
  utilization: '٣ — تحليل الاستغلال',
  hoursAnalysis: '٤ — تحليل الساعات',
  lostHours: '٥ — تحليل الساعات المهدرة',
  supervisorPerformance: '٦ — أداء المشرفين',
  supervisorRisk: '٧ — تحليل مخاطر المشرفين',
  recruitment: '٨ — تحليل التعيين',
  attrition: '٩ — تحليل التسرب',
  growthOpportunities: '١٠ — فرص النمو',
  growthExpansion: 'مؤشرات النمو والتوسع',
  formulaAudit: 'مراجعة المعادلات التشغيلية',
  hoursRoadmap: '١١ — خارطة 2200 ساعة يومياً',
  aiInsights: '١٢ — رؤى الإدارة التشغيلية',
  dataValidation: 'تدقيق البيانات والتحقق',
  dataIntegrityReport: 'تقرير سلامة البيانات',
  ghostRiderAudit: 'تدقيق Ghost Riders',
  joinDateAudit: 'تدقيق تاريخ الانضمام',
  codeNormalizationAudit: 'Code Normalization Audit',
  postNormalizationValidation: 'POST-NORMALIZATION VALIDATION REPORT',
  finalKpiAccuracyAudit: 'FINAL KPI ACCURACY AUDIT',
  operationalHealth: 'درجة صحة التشغيل',
  operationalTruthIntelligence: 'ذكاء الحقيقة التشغيلية',

  totalRegistered: 'إجمالي الطيارين المسجلين',
  totalAssigned: 'المعيّنون للمشرفين',
  activeRiders: 'الطيارون النشطون',
  inactiveRiders: 'الطيارون غير النشطين',
  suspendedRiders: 'الطيارون الموقوفون',
  approvedResignations: 'عدد الإقالات المعتمدة',
  newJoins: 'انضمام جديد (الفترة)',
  utilizationRate: 'معدل الاستغلال',
  attritionRate: 'نسبة التسرب',
  monthlyAttrition: 'متوسط التسرب الشهري',

  healthExcellent: 'ممتاز',
  healthGood: 'جيد',
  healthNeedsAction: 'يحتاج تدخل',
  healthDanger: 'خطر',

  bucket0: '٠ ساعة',
  bucketLt2: 'أقل من ٢ ساعة',
  bucket2to4: '٢ إلى ٤ ساعات',
  bucket4to6: '٤ إلى ٦ ساعات',
  bucket6to8: '٦ إلى ٨ ساعات',
  bucket8to10: '٨ إلى ١٠ ساعات',
  bucketGt10: 'أكثر من ١٠ ساعات',

  lostNoOperation: 'ساعات مهدرة بسبب عدم التشغيل',
  lostWeakOperation: 'ساعات مهدرة بسبب ضعف التشغيل',
  lostResignations: 'ساعات مهدرة بسبب الإقالات',

  source: 'مصدر البيانات',
  sheet: 'اسم الشيت',
  columns: 'الأعمدة المستخدمة',
  records: 'عدد السجلات',
  formula: 'طريقة الحساب',
} as const;

export const HOUR_BUCKET_DEFS_AR = [
  { key: '0', label: '٠ ساعة' },
  { key: 'lt2', label: 'أقل من ٢ ساعة' },
  { key: '2-4', label: '٢ إلى ٤ ساعات' },
  { key: '4-6', label: '٤ إلى ٦ ساعات' },
  { key: '6-8', label: '٦ إلى ٨ ساعات' },
  { key: '8-10', label: '٨ إلى ١٠ ساعات' },
  { key: 'gt10', label: 'أكثر من ١٠ ساعات' },
] as const;
